# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='products')),
                ('category', models.CharField(choices=[('IT', 'IT & Gadget'), ('EL', 'Electronics'), ('FA', 'Fashion')], max_length=2)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
